//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SimCoupe.rc
//
#define IDI_MAIN                        1
#define IDI_MISC                        3
#define IDI_HARDWARE                    5
#define IDI_MEMORY                      13
#define IDI_PORT                        23
#define IDI_MOUSE                       100
#define IDR_MENU                        101
#define IDI_JOYSTICK                    102
#define IDD_EXPORT                      107
#define IDD_ABOUT                       108
#define IDI_FLOPPY                      110
#define IDD_NEW_DISK                    119
#define IDC_CURSOR                      123
#define IDI_DISPLAY                     144
#define IDD_PAGE_PARALLEL               164
#define IDD_PAGE_SOUND                  165
#define IDD_PAGE_DISPLAY                166
#define IDD_PAGE_JOYSTICK               167
#define IDD_PAGE_SYSTEM                 168
#define IDD_PAGE_INPUT                  169
#define IDD_PAGE_MIDI                   170
#define IDD_PAGE_MISC                   171
#define IDD_PAGE_DISKS                  172
#define IDI_NETWORK                     173
#define IDD_PAGE_FNKEYS                 173
#define IDI_FNKEYS                      175
#define IDD_NEW_FNKEY                   177
#define IDD_IMPORT                      178
#define IDD_PAGE_DRIVES                 179
#define IDD_HARDDISK                    180
#define IDB_SIMCOUPE                    185
#define IDI_KEYBOARD                    200
#define IDI_CLOCK                       201
#define IDI_PRINTER                     225
#define IDE_PAGE                        1001
#define IDE_SIDES                       1001
#define IDE_STATION_ID                  1001
#define IDE_ROM                         1001
#define IDC_COMPRESS                    1002
#define IDC_ALT_FOR_CNTRL               1002
#define IDE_TRACKS                      1003
#define IDE_FILE                        1004
#define IDE_SECTORS                     1004
#define IDC_ALTGR_FOR_EDIT              1005
#define IDE_NEWFILE                     1005
#define IDE_TOTALSIZE                   1006
#define IDE_OFFSET                      1007
#define IDC_SPIN1                       1015
#define IDS_SIDES                       1015
#define IDR_BASIC_ADDRESS               1016
#define IDR_PAGE_OFFSET                 1017
#define IDS_TRACKS                      1018
#define IDS_SECTORS                     1019
#define IDS_TOTALSIZE                   1020
#define IDB_SAVE_AS                     1021
#define IDE_ADDRESS                     1022
#define IDE_LENGTH                      1023
#define IDC_SIDES                       1039
#define IDC_TRACKS                      1040
#define IDC_SECTORS                     1041
#define IDC_SECTORSIZE                  1042
#define IDR_DISK_TYPE_DSK               1045
#define IDR_DISK_TYPE_SAD               1046
#define IDR_DISK_TYPE_SDF               1047
#define IDC_MOUSE_ENABLED               1055
#define IDC_JOYSTICK1                   1056
#define IDC_JOYSTICK2                   1057
#define IDC_DEADZONE_1                  1058
#define IDC_DEADZONE_2                  1059
#define IDC_STEREO                      1060
#define IDC_FREQ                        1062
#define IDC_MAIN_MEMORY                 1064
#define IDC_EXTERNAL_MEMORY             1065
#define IDC_MIDI_OUT                    1066
#define IDC_SAMBUS_CLOCK                1067
#define IDC_SAMPLE_SIZE                 1069
#define IDC_MIDI_IN                     1070
#define IDC_KEYBOARD_MAPPING            1073
#define IDC_PARALLEL_2                  1074
#define IDC_PARALLEL_1                  1075
#define IDC_PRINTERS                    1076
#define IDC_WINDOW_SCALING              1078
#define IDC_RATIO_5_4                   1080
#define IDC_FULLSCREEN_DEPTH            1081
#define IDC_SAASOUND_ENABLED            1082
#define IDC_DALLAS_CLOCK                1083
#define IDC_CLOCK_SYNC                  1084
#define IDC_FRAMESKIP_AUTOMATIC         1086
#define IDC_FRAMESKIP                   1087
#define IDC_PROFILE                     1088
#define IDC_STATUS                      1089
#define IDC_BORDERS                     1089
#define IDC_DRIVE_LIGHTS                1090
#define IDC_SURFACE_TYPE                1090
#define IDC_SYNC                        1091
#define IDC_PAUSE_INACTIVE              1091
#define IDC_FAST_RESET                  1092
#define IDC_FULLSCREEN                  1092
#define IDC_BEEPER                      1092
#define IDC_CTRL                        1092
#define IDC_NON_REAL_WORLD              1092
#define IDC_PRINTER_ONLINE              1092
#define IDC_MIDI                        1093
#define IDC_SHIFT                       1093
#define IDC_LATENCY                     1097
#define IDC_DRIVE1                      1098
#define IDC_DRIVE2                      1099
#define IDC_STRETCH_TO_FIT              1106
#define IDC_SCANLINES                   1107
#define IDB_ATOM                        1107
#define IDB_DELETE                      1108
#define IDB_SDIDE                       1108
#define IDB_EDIT                        1109
#define IDB_YATBUS                      1109
#define IDB_ADD                         1110
#define IDL_FNKEYS                      1111
#define IDC_KEY                         1113
#define IDC_ACTION                      1115
#define IDS_FREQ                        1116
#define IDS_SAMPLE_SIZE                 1117
#define IDS_LATENCY                     1118
#define IDS_WINDOW_SCALING              1119
#define IDS_FULLSCREEN_DEPTH            1120
#define IDC_SOUND_ENABLED               1121
#define IDI_SAM                         1122
#define IDB_BROWSE                      1123
#define IDS_LENGTH                      1124
#define IDB_SAVE                        1126
#define IDC_INSERT_INTO                 1127
#define IDB_FLUSH_PRINT_JOB             1129
#define IDC_TURBO_LOAD                  1130
#define IDC_SENSITIVITY                 1131
#define IDS_SENSITIVITY                 1132
#define IDC_ALT                         1133
#define ID_HOMEPAGE                     1134
#define IDC_FLOPPY1                     1135
#define IDC_FLOPPY2                     1136
#define IDC_ATOM                        1137
#define IDC_SDIDE                       1138
#define IDC_YATBUS                      1139
#define IDB_FLOPPY1                     1140
#define IDB_FLOPPY2                     1141
#define IDB_CREATE                      1142
#define IDE_FILEPATH                    1143
#define IDE_CYLINDERS                   1144
#define IDE_HEADS                       1145
#define IDS_CYLINDERS                   1146
#define IDS_HEADS                       1147
#define IDI_SOUND                       3004
#define IDI_MIDI                        4381
#define IDM_FILE_EXIT                   40001
#define IDM_HELP_ABOUT                  40050
#define IDM_HELP_GENERAL                40051
#define IDM_FILE_FLOPPY1_INSERT         40092
#define IDM_FILE_FLOPPY1_EJECT          40093
#define IDM_FILE_FLOPPY2_INSERT         40095
#define IDM_FILE_FLOPPY2_EJECT          40096
#define IDM_FILE_IMPORT_DATA            40107
#define IDM_FILE_EXPORT_DATA            40108
#define IDM_FILE_NEW_DISK               40109
#define IDM_FILE_FLOPPY1_SAVE_CHANGES   40119
#define IDM_FILE_FLOPPY2_SAVE_CHANGES   40120
#define IDM_FILE_FLOPPY1_DEVICE         40134
#define IDM_FILE_FLOPPY2_DEVICE         40135
#define IDM_TOOLS_OPTIONS               40147
#define IDM_TOOLS_FLUSH_PRINTER         40152
#define IDM_TOOLS_PRINTER_ONLINE        40154

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         40155
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
