name: macOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ macos-latest, macos-13 ]

    steps:
    - uses: actions/checkout@v4

    - name: Install SDL2
      run: |
        curl -LO https://github.com/libsdl-org/SDL/releases/download/release-${SDL_VERSION}/SDL2-${SDL_VERSION}.dmg
        hdiutil attach SDL2-${SDL_VERSION}.dmg
        sudo cp -r /Volumes/SDL2/SDL2.framework /Library/Frameworks/
      env:
        SDL_VERSION: "2.32.6"

    - name: Configure
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build
      env:
        MAKEFLAGS: "-j3"
